services:
  db:
    env_file:
      - .env
    image: postgres:18.1-alpine
    container_name: mili_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio
    container_name: mili_minio
    env_file:
      - .env
    ports:
      - "${S3_PORT}:9000"
      - "${S3_ADMIN_PORT}:9001"
    environment:
      - MINIO_ROOT_USER=${S3_USER}
      - MINIO_ROOT_PASSWORD=${S3_PASSWORD}
    volumes:
      - minio_data:/data
    restart: unless-stopped
    command: server /data --console-address ":${S3_ADMIN_PORT}"
volumes:
  pgdata:
  minio_data:
