import type { Metadata } from "next";

import "@/app/dashboard.css";

import { ThemeProvider } from "next-themes";

import { Toaster } from "@/components/dashboard/ui/sonner";
import { FontDashboard } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Yatak dashboard",
  description: "Generated by create next app",
};

const DashboardLayout = ({ children }: Readonly<LayoutProps<"/admin">>) => {
  return (
    <html dir="rtl" lang="fa" suppressHydrationWarning>
      <body className={FontDashboard.variable}>
        <ThemeProvider attribute="class">
          <main className="w-full">
            {children}
            <Toaster position="top-center" />
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
};
export default DashboardLayout;
