import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<LayoutProps<"/">>) {
  return (
    <html dir="rtl" lang="en">
      <body className="container mx-auto py-6">{children}</body>
    </html>
  );
}
